{
 "title": "New dashboard",
 "time": { "from": "2025-05-08T08:07:23.207Z", "to": "2025-05-08T08:15:42.298Z" },
 "panels": [
  {
   "title": "MQ2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT mq2, time FROM fire_gas;"
    }
   ]
  },
  {
   "title": "Danger Indicator (Fire and gas at the same time)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "Select (fire/4095)*100 as fire, mq2, time from fire_gas;"
    }
   ]
  },
  {
   "title": "Fire Sensor Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT fire, time FROM fire_gas;"
    }
   ]
  }
 ]
}